package com.mldz.core.entities


data class MovieDetails(
    var id: String = "",
    var title: String = "",
    var fullTitle: String = "",
    var type: String = "",
    var year: String = "",
    var image: String = "",
    var releaseDate: String = "",
    var runtimeMins: String = "",
    var runtimeStr: String = "",
    var plot: String = "",
    var plotLocal: String = "",
    var plotLocalIsRtl: Boolean = false,
    var awards: String = "",
    var directors: String = "",
    var writers: String = "",
    var stars: String = "",
    var fullCast: String? = "",
    var genres: String = "",
    var companies: String = "",
    var countries: String = "",
    var languages: String = "",
    var contentRating: String = "",
    var imDbRating: String = "",
    var imDbRatingVotes: String = "",
    var metacriticRating: String = "",
    var ratings: String? = "",
    var wikipedia: String? = "",
    var posters: String? = "",
    var images: String? = "",
    var trailer: String? = "",
    var tagline: String = "",
    var errorMessage: String? = "",

//    @SerializedName("directorList"     ) var directorList     : ArrayList<DirectorList> = arrayListOf(),
//    @SerializedName("writerList"       ) var writerList       : ArrayList<WriterList>   = arrayListOf(),
//    @SerializedName("starList"         ) var starList         : ArrayList<StarList>     = arrayListOf(),
//    @SerializedName("actorList"        ) var actorList        : ArrayList<ActorList>    = arrayListOf(),
//    @SerializedName("genreList"        ) var genreList        : ArrayList<GenreList>    = arrayListOf(),
//    @SerializedName("companyList"      ) var companyList      : ArrayList<CompanyList>  = arrayListOf(),
//    @SerializedName("countryList"      ) var countryList      : ArrayList<CountryList>  = arrayListOf(),
//    @SerializedName("languageList"     ) var languageList     : ArrayList<LanguageList> = arrayListOf(),
//    @SerializedName("boxOffice"        ) var boxOffice        : BoxOffice?              = BoxOffice(),
//    @SerializedName("similars"         ) var similars         : ArrayList<Similars>     = arrayListOf(),
)
