package com.mldz.data2.api.model

import com.google.gson.annotations.SerializedName


data class MovieResponse(
    @SerializedName("id"               ) var id               : String                 = "",
    @SerializedName("title"            ) var title            : String                 = "",
    @SerializedName("originalTitle"    ) var originalTitle    : String                 = "",
    @SerializedName("fullTitle"        ) var fullTitle        : String                 = "",
    @SerializedName("type"             ) var type             : String                 = "",
    @SerializedName("year"             ) var year             : String                 = "",
    @SerializedName("image"            ) var image            : String                 = "",
    @SerializedName("releaseDate"      ) var releaseDate      : String                 = "",
    @SerializedName("runtimeMins"      ) var runtimeMins      : String                 = "",
    @SerializedName("runtimeStr"       ) var runtimeStr       : String                 = "",
    @SerializedName("plot"             ) var plot             : String                 = "",
    @SerializedName("plotLocal"        ) var plotLocal        : String                 = "",
    @SerializedName("plotLocalIsRtl"   ) var plotLocalIsRtl   : Boolean                = false,
    @SerializedName("awards"           ) var awards           : String                 = "",
    @SerializedName("directors"        ) var directors        : String                 = "",
//    @SerializedName("directorList"     ) var directorList     : ArrayList<DirectorList> = arrayListOf(),
    @SerializedName("writers"          ) var writers          : String                 = "",
//    @SerializedName("writerList"       ) var writerList       : ArrayList<WriterList>   = arrayListOf(),
    @SerializedName("stars"            ) var stars            : String                 = "",
//    @SerializedName("starList"         ) var starList         : ArrayList<StarList>     = arrayListOf(),
//    @SerializedName("actorList"        ) var actorList        : ArrayList<ActorList>    = arrayListOf(),
    @SerializedName("fullCast"         ) var fullCast         : String?                 = "",
    @SerializedName("genres"           ) var genres           : String                 = "",
//    @SerializedName("genreList"        ) var genreList        : ArrayList<GenreList>    = arrayListOf(),
    @SerializedName("companies"        ) var companies        : String                 = "",
//    @SerializedName("companyList"      ) var companyList      : ArrayList<CompanyList>  = arrayListOf(),
    @SerializedName("countries"        ) var countries        : String                 = "",
//    @SerializedName("countryList"      ) var countryList      : ArrayList<CountryList>  = arrayListOf(),
    @SerializedName("languages"        ) var languages        : String                 = "",
//    @SerializedName("languageList"     ) var languageList     : ArrayList<LanguageList> = arrayListOf(),
    @SerializedName("contentRating"    ) var contentRating    : String                 = "",
    @SerializedName("imDbRating"       ) var imDbRating       : String                 = "",
    @SerializedName("imDbRatingVotes"  ) var imDbRatingVotes  : String                 = "",
    @SerializedName("metacriticRating" ) var metacriticRating : String                 = "",
    @SerializedName("ratings"          ) var ratings          : String                 = "",
    @SerializedName("wikipedia"        ) var wikipedia        : String                 = "",
    @SerializedName("posters"          ) var posters          : String                 = "",
    @SerializedName("images"           ) var images           : String                 = "",
    @SerializedName("trailer"          ) var trailer          : String                 = "",
//    @SerializedName("boxOffice"        ) var boxOffice        : BoxOffice?              = BoxOffice(),
    @SerializedName("tagline"          ) var tagline          : String?                 = "",
    @SerializedName("keywords"         ) var keywords         : String                 = "",
    @SerializedName("keywordList"      ) var keywordList      : ArrayList<String>       = arrayListOf(),
//    @SerializedName("similars"         ) var similars         : ArrayList<Similars>     = arrayListOf(),
    @SerializedName("tvSeriesInfo"     ) var tvSeriesInfo     : String                 = "",
    @SerializedName("tvEpisodeInfo"    ) var tvEpisodeInfo    : String                 = "",
    @SerializedName("errorMessage"     ) var errorMessage     : String                 = ""
)
